# Generated by Django 5.1 on 2024-08-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_post_category_categorytranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
